name: Unit and Integration tests
run-name: Running implemented tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Install repo packages
        run: npm install --force
      - name: Run tests with coverage
        run: npm test -- --coverage --coverageReporters=text-lcov

      - name: Generate coverage badge
        id: coverage-badge
        run: bash -c 'npx jest-coverage-badge'

      - name: Save coverage badge
        run: echo "::set-output name=coverage-badge::$(cat coverage-badge.svg)"
        if: always()
